# Generated by Django 4.2.3 on 2024-03-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEDEAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('cierre_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultimo_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variacion_diaria', models.CharField(max_length=50)),
                ('volumen_efectivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volumen_nominal', models.IntegerField()),
                ('tipo_cotizacion', models.CharField(max_length=3)),
                ('cantidad_nominal_compra', models.IntegerField(default=0)),
                ('cantidad_nominal_venta', models.IntegerField(default=0)),
                ('cantidad_operaciones', models.CharField(default=0, max_length=50)),
                ('estado', models.CharField(blank=True, default='', max_length=50)),
                ('ex', models.CharField(blank=True, default='', max_length=3)),
                ('hora_cotizacion', models.TimeField(default='00:00:00', max_length=8)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_promedio_ponderado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('simbolo', models.CharField(default=None, max_length=10)),
                ('tendencia', models.IntegerField(default=None)),
                ('vencimiento', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
