# Generated by Django 4.2.3 on 2024-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedear',
            name='hora_cotizacion',
            field=models.TimeField(default='00:00', max_length=6),
        ),
    ]
