# Generated by Django 4.2.3 on 2024-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0002_alter_cedear_hora_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedear',
            name='hora_cotizacion',
            field=models.CharField(default='00:00:00', max_length=12),
        ),
    ]
