# Generated by Django 4.2.3 on 2024-03-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0003_alter_cedear_hora_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cedear',
            options={'ordering': ['especie']},
        ),
    ]
