# Generated by Django 4.2.3 on 2024-03-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0004_alter_cedear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedear',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
