# Generated by Django 4.2.3 on 2024-03-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0005_cedear_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedear',
            name='simbolo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
