# Generated by Django 4.2.3 on 2024-03-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0007_alter_cedear_tendencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('mercado', models.CharField(max_length=10)),
                ('ultimo_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apertura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen', models.BigIntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
