# Generated by Django 4.2.3 on 2024-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0008_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='simbolo_cedears',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
