# Generated by Django 4.2.3 on 2024-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisActions', '0009_accion_simbolo_cedears'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='recomendacion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accion',
            name='simbolo_cedears',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
